name: sebha
description: This project to rewrite native kotline SebhaCounter app

publish_to: 'none' #

version: 2.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: any
  get_storage: ^2.1.1
  google_fonts:

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:


  uses-material-design: true

  assets:
     - assets/images/

